---
anchors:
-   govc: &govc
        GOVC_URL: ((host_ip))
        # vCenter credentials
        GOVC_USERNAME: ((host_username))
        GOVC_PASSWORD: ((host_password))
        # disable cert validation
        GOVC_INSECURE: true

resource_types:
- name: cron-resource
  type: docker-image
  source:
    repository: cftoolsmiths/cron-resource
    tag: latest

resources:
-   name: repo
    type: git
    check_every: 10m
    source:
        uri: https://github.com/laidbackware/lab-power-saver.git
        branch: master

-   name: power-on-trigger
    type: cron-resource
    check_every: 10m
    source:
        expression: ((power_on_expression)) # Run at 8am Monday to Friday
        location: ((time_zone))

-   name: power-off-trigger
    type: cron-resource
    check_every: 10m
    source:
        expression: ((power_off_expression)) # Run at 6pm Monday to Friday
        location: ((time_zone))

jobs:
-   name: suspend-and-power-down
    plan:
    -   get: repo
    -   get: power-off-trigger
        trigger: true
    -   task: suspend-and-power-down
        params:
            << : *govc
        file: repo/tasks/put-to-sleep/task.yml

-   name: power-up
    plan:
    -   get: repo
    -   get: power-on-trigger
        trigger: true
    -   task: wake-up-host
        params:
            HOST_IP: ((host_ip))
            HOST_CIDR_INT: ((host_cidr_int))
            HOST_MAC: ((host_mac))
        file: repo/tasks/wake-up/task.yml

    -   task: resume-all-vms
        params:
            << : *govc
        file: repo/tasks/resume-vms/task.yml